kramdown:
  input: GFM
  hard_wrap: false
encoding: utf-8
gems:
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag
exclude:
  - Gemfile*
  - CNAME
  - node_modules
  - npm-debug.log
sass:
  style: compressed
permalink: /:categories/:year/:month/:slug/
timezone: Europe/Paris
defaults:
-
  scope:
    path: ""
    type: "pages"
  values:
    layout: page
-
  scope:
    path: ""
    type: "posts"
  values:
    layout: post
